[package]
name = "CodeGenLib"
version = "0.1.0-beta0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faerie = "0.16.0"
target-lexicon = "0.11"
